spring.application.name=chem-lab
server.address= 0.0.0.0
server.port= 8080

spring.datasource.url= jdbc:postgresql://localhost:5432/chem-lib
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password= ${DB_PASSWORD}
spring.flyway.enabled= true
spring.flyway.locations= classpath:db/migration
spring.flyway.clean-on-validation-error= false
spring.flyway.clean-disabled= true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true